django_1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path ("", include ("inicio.urls"))
]

inicio/urls.py
from django.urls import path 
from inicio.views import propiedades, inicio, crear_propiedad

app_name = "inicio"

urlpatterns = [
    path ("propiedad", propiedades),
    path ("", inicio, name= "inicio" ),
    path ("crear-propiedad", crear_propiedad, name= "crear_propiedad")
]
    

inicio/models.py
from django.db import models


class Propiedades (models.Model):
    metros_cuadrados = models.IntegerField ()
    ubicacion = models.CharField (max_length=20)
    precio = models.CharField (max_length=20)

    def __str__(self):
        return f"{self.precio} {self.ubicacion} {self.metros_cuadrados}"  

inicio/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.shortcuts import render
from inicio.models import Propiedades


def propiedades (request):
    return HttpResponse ("propiedades")

def inicio (request):
    #return HttpResponse ("soy la pantalla de inicio")
    return render (request, "inicio/index.html")

def crear_propiedad (request):
   propiedad = Propiedades (metros_cuadrados = 300, ubicacion= "palermo", precio= "300.000 $")
   propiedad.save()
   return render (request, "inicio/crear_propiedad.html", {}) 

inicio/templates/index.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Stylish Portfolio - Start Bootstrap Template</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Simple line icons-->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/simple-line-icons/2.5.5/css/simple-line-icons.min.css" rel="stylesheet" />
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href= {% static "css/styles.css" %} rel="stylesheet" />
    </head>
    <body id="page-top">
        <!-- Navigation-->
        <nav id="sidebar-wrapper">
            <ul class="sidebar-nav">
                <li class="sidebar-brand"><a href="#page-top">Start Bootstrap</a></li>
                <li class="sidebar-nav-item"><a href="#page-top">Home</a></li>
                <li class="sidebar-nav-item"><a href="#about">About</a></li>
                <li class="sidebar-nav-item"><a href="#services">Services</a></li>
                <li class="sidebar-nav-item"><a href="#portfolio">Portfolio</a></li>
                <li class="sidebar-nav-item"><a href="#contact">Contact</a></li>
            </ul>
        </nav>
        <!-- Header-->
        <header class="masthead d-flex align-items-center">
            <div class="container px-4 px-lg-5 text-center">
                <h1 class="mb-1">Inmoviliaria Alonzo</h1>
                <h3 class="mb-5"><em>Las mejores propiedades al mejor precio</em></h3>
            </div>
        </header>
        <!-- About-->
        <!-- Services-->
        <!-- Callout-->
        <footer class="footer text-center">
            <div class="container px-4 px-lg-5">
                <ul class="list-inline mb-5">
                    <li class="list-inline-item">
                        <a class="social-link rounded-circle text-white mr-3" href="#!"><i class="icon-social-facebook"></i></a>
                    </li>
                    <li class="list-inline-item">
                        <a class="social-link rounded-circle text-white mr-3" href="#!"><i class="icon-social-twitter"></i></a>
                    </li>
                    <li class="list-inline-item">
                        <a class="social-link rounded-circle text-white" href="#!"><i class="icon-social-github"></i></a>
                    </li>
                </ul>
                <p class="text-muted small mb-0">Copyright &copy; Your Website 2023</p>
            </div>
        </footer>
        <!-- Scroll to Top Button-->
        <a class="scroll-to-top rounded" href="#page-top"><i class="fas fa-angle-up"></i></a>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
    </body>
</html>

inicio/templates/inicio/crear_propiedad.html
{% extends "base.html" %}

{% block title_head %}
    Inmoviliaria Alonzo
{% endblock title_head %}
{% block h1_header%} Inmoviliaria Alonzo {% endblock h1_header%}

{% block h3_header %} Las mejores propiedades al mejor precio {% endblock h3_header %}

{% block main%} Inmoviliaria Alonzo  {% endblock main%}

inicio/templates/inicio/index.html
{% extends "base.html" %}

{% block title_head %}
    inicio
{% endblock title_head %}

{% block h1_header%} inicio {% endblock h1_header%}

{% block h3_header %}  {% endblock h3_header %}

{% block main %}  {% endblock main %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>
            {% block title_head %}
             template base 
            {% endblock title_head %}
        </title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Simple line icons-->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/simple-line-icons/2.5.5/css/simple-line-icons.min.css" rel="stylesheet" />
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href= {% static "css/styles.css" %} rel="stylesheet" />
    </head>
    <body id="page-top">
        <!-- Navigation-->
        <div class="container">
            <div class="container">
                <a class="navbar-brand"><a href= {% url "inicio:inicio" %} > inicio</a>
                <a class="navbar-brand"><a href= {% url "inicio:crear_propiedad" %} > crear propiedad</a>   
            </div>
        </div>
        <!-- Header-->
        <header class="masthead d-flex align-items-center">
            <div class="container px-4 px-lg-5 text-center">
                <h1> {% block h1_header%} hola {% endblock h1_header%} </h1> 
                <h3> {% block h3_header %} hola {% endblock h3_header %}  </em></h3>
            </div>    
        </header>
        <main> 
            {% block main %} listado {% endblock main %}
        </main>
        <footer class="footer text-center">
            <div class="container px-4 px-lg-5">
                <ul class="list-inline mb-5">
                    <li class="list-inline-item">
                        <a class="social-link rounded-circle text-white mr-3" href="#!"><i class="icon-social-facebook"></i></a>
                    </li>
                    <li class="list-inline-item">
                        <a class="social-link rounded-circle text-white mr-3" href="#!"><i class="icon-social-twitter"></i></a>
                    </li>
                    <li class="list-inline-item">
                        <a class="social-link rounded-circle text-white" href="#!"><i class="icon-social-github"></i></a>
                    </li>
                </ul>
                <p class="text-muted small mb-0">Copyright &copy; Your Website 2023</p>
            </div>
        </footer>
        <!-- Scroll to Top Button-->
        <a class="scroll-to-top rounded" href="#page-top"><i class="fas fa-angle-up"></i></a>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
    </body>
</html>